@startuml
start
:早上;
if (周一/周二/周三/周四/周五)
  if (周三/周四) then (yes)
     :1-7x2;
  else (no)
     :1-7x3;
  endif
  :剿灭->龙门市区x1;
  if (周一)
    :素材x2(粉碎防御);
  elseif (周二)
    :素材x2(空中威胁);
  elseif (周五)
    :素材x2(战术演习);
  endif
  :JT8-2x1;
elseif (周六)
    :1-7x3;
    :剿灭->切尔诺伯格x1;
    :素材x2(战术演习);
    :JT8-2x1;
    if (理智补剂+100)
      :1-7x1;
      :素材x3(战术演习);
    endif
elseif (周日)
    :素材x4(战术演习);
    if (理智补剂+100)
      :JT8-2x1;
      :6-11x1;
      :素材x2(战术演习);
    endif
endif
:晚上;
if (周一)
    :素材x4(粉碎防御);
  elseif (周二)
    :素材x4(空中威胁);
  elseif (周三/周四);
    :素材x4(货物运送);
  elseif (周五/周六)
    :素材x4(战术演习);
  elseif (周日
    :1-7x1;
    :素材x3(战术演习);
    :JT8-2x1;
  endif

@enduml
