@startuml
start
  :获取公招标签;
if (存在"高资")
  :单选"高资";
elseif (存在"资深")
  :单选"资深";
elseif (存在五星必出组合)
  :选择五星必出组合;
elseif (存在"机械小车")
  :单选"机械小车";
  :定时3小时50分钟;
  stop
elseif (存在四星标签)
  :选择所有四星标签;
elseif (存在四星必出组合)
  :选择四星必出组合;
elseif (可刷新标签)
  :刷新标签;
  stop
else
  :不选择任何标签;
endif
:定时8/9小时(随机);
stop
@enduml
