@startuml
登录 -> 主页:判断账号登录
queue 公共招募
control 理智检查
boundary 主页
queue 每日队列
queue 基建检查
entity 每日任务
主页 -> 公共招募:每日收取并开始两个
主页 -> 理智检查:OCR数字
理智检查 -> 每日队列:开始一个任务
每日队列 -> 主页:完成一个任务
主页 -> 基建检查:完成所有任务
主页 -> 每日任务:完成所有任务
@enduml
