name: Python Pull Request Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CHECK-CODE:   
    name: Quality check    
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v1

    - name: Set up Python        
      uses: actions/setup-python@master        
      with: 
        python-version: 3.8      
          
    - name: Run unit tests        
      run: |          
        pip install pytest    
        pytest
      
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      continue-on-error: true        
      with:
      reporter: 'github-pr-review'        
      env:          
        GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
